#!/bin/bash

if [ "$(uname)" == "Darwin" ];then
	g++ main.cpp protocol.cpp connection.cpp race.cpp simulation.cpp session.cpp -std=c++11 -I jsoncons/src/ -o plusbot -l boost_system -l boost_thread-mt -l readline
else
	g++ main.cpp protocol.cpp connection.cpp race.cpp simulation.cpp session.cpp -std=c++11 -I jsoncons/src/ -o plusbot -l boost_system -l boost_thread -l readline
fi

